version: '3.8'

services:
  api:
    build: .
    container_name: subcontractor_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - mongo
    command: >
      bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./dataset:/dataset
    restart: unless-stopped

  celery:
    build: .
    container_name: subcontractor_celery
    env_file:
      - .env
    depends_on:
      - redis
      - mongo
    command: >
      celery -A workers.tasks worker --loglevel=info
    volumes:
      - ./dataset:/dataset
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: subcontractor_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: subcontractor_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: unless-stopped
volumes:
  redis_data:
  mongo_data:
